### ISSUE TITLE
Feature request: updating Deno version in GitHub actions

### ISSUE THREAD

**Issue by harrysolovay** [hayd/deno-udd#49]
Huge fan of this project!

Was wondering if you'd consider extending its functionality to cover Deno version text in non-TS files (in particular GitHub actions).

```yml
name: Test
on:
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11.0, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.17.1 # <--
      - run: scripts/test.ts
```

I'd understand if this is out of scope, as there's no generalized & obvious way to identify some version text as a Deno version. Perhaps it could apply––at first––only to `denoland/setup-deno` jobs.

Thank you for your consideration!
